-- Create bookings table for basketball scheduler
CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  day TEXT NOT NULL,
  date TEXT,
  time TEXT NOT NULL,
  name TEXT NOT NULL,
  is_recurring BOOLEAN DEFAULT false,
  exceptions TEXT[] DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_bookings_day_time ON bookings(day, time);
CREATE INDEX IF NOT EXISTS idx_bookings_date_time ON bookings(date, time);

-- Enable Row Level Security (optional - remove if you want public access)
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;

-- Create policy to allow all operations (adjust as needed for your security requirements)
CREATE POLICY "Allow all access to bookings" ON bookings
  FOR ALL USING (true)
  WITH CHECK (true);
